// AUTOGENERATED - DO NOT MODIFY

// Timestamp changes on every export, ensuring the dev server detects a rebuild
export const BUILD_TIME = '2026-07-31 10:04:35.162276848 -0700 PDT m=+2.469633920';

// App manifest — consumed by the Dashboard to configure the app
export default {
  "$schema": "https://stripe.com/stripe-app.schema.json",
  "allowed_redirect_uris": [
    "https://tastatur.dev/stripe/connect/callback",
    "https://localhost:3443/stripe/connect/callback"
  ],
  "distribution_type": "public",
  "icon": "./icon_32.png",
  "id": "dev.tastatur.revenue",
  "name": "Tastatur",
  "permissions": [
    {
      "permission": "customer_read",
      "purpose": "Match your Stripe customers to their signup so revenue can be attributed to the marketing channel that produced them."
    },
    {
      "permission": "checkout_session_read",
      "purpose": "Read the attribution metadata your checkout attaches, which is how a payment is tied back to a first visit."
    },
    {
      "permission": "subscription_read",
      "purpose": "Follow subscription starts, changes and cancellations to compute MRR per acquisition channel."
    },
    {
      "permission": "invoice_read",
      "purpose": "Record paid and failed invoices as the revenue behind each channel."
    },
    {
      "permission": "charge_read",
      "purpose": "Record refunds so attributed revenue goes down when money is returned."
    },
    {
      "permission": "dispute_read",
      "purpose": "Record chargebacks so attributed revenue reflects disputed payments."
    },
    {
      "permission": "event_read",
      "purpose": "Receive webhook events for the objects above as they change, instead of polling your account."
    }
  ],
  "sandbox_install_compatible": true,
  "stripe_api_access_type": "oauth",
  "version": "0.0.1"
};
