class User < ApplicationRecord
  include PubliclyIdentified
  public_identifier

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :confirmable, :lockable, :trackable,
         :recoverable, :rememberable, :validatable

  # The outstanding two-factor code, bcrypted. `validations: false` because the
  # code is generated by TwoFactor::IssueChallenge and never typed into a form,
  # so there is nothing for a presence or confirmation validator to protect —
  # and a validation here would refuse to save a user whose code has been
  # cleared, which is the normal resting state.
  has_secure_password :two_factor_code, validations: false

  has_many :memberships, dependent: :destroy
  has_many :accounts, through: :memberships
  has_many :sites, through: :accounts

  # Destroyed with the user: a trusted device is meaningless without the account
  # it lets you into, and leaving orphans behind would keep a valid-looking
  # digest in the table forever.
  has_many :trusted_devices, dependent: :destroy

  scope :administrators, -> { where(admin: true) }
  scope :by_recency, -> { order(created_at: :desc) }

  # Case-insensitive substring match on email or name, for the admin console's
  # "find the person who just emailed us" box. Deliberately not a full-text
  # index: the table is small, support searches are rare, and an unused index on
  # a table Devise writes to on every sign-in is a cost with no reader.
  scope :matching, lambda { |query|
    next all if query.blank?

    term = "%#{sanitize_sql_like(query.to_s.strip)}%"
    where("email ILIKE :t OR name ILIKE :t", t: term)
  }

  # Devise's lockable sets locked_at; there is no predicate that reads well in a
  # view, and `access_locked?` also consults the unlock strategy.
  def locked? = locked_at.present?

  def confirmed? = confirmed_at.present?

  # The devices the account page lists. Empty — rather than merely unrendered —
  # when two-factor is off, so nothing stale can be shown by a screen that
  # forgets to check the flag first. Expired rows are excluded because a device
  # that no longer skips anything is not a device to reassure somebody about.
  def visible_trusted_devices
    return TrustedDevice.none unless two_factor_enabled?

    trusted_devices.active.by_recency
  end

  # Is there a code outstanding that has not expired?
  #
  # Reads the expiry rather than the digest, because a code that has run out of
  # time is not "a challenge that failed" — it is no challenge at all, and the
  # difference decides whether the screen says "that code is wrong" or "that code
  # has expired, here is another".
  def two_factor_challenge_pending?
    two_factor_code_digest.present? &&
      two_factor_code_expires_at.present? &&
      two_factor_code_expires_at > Time.current
  end

  # Every user gets a personal account on signup, so `default_account` is only
  # nil for a user whose accounts have all been deleted.
  def default_account
    accounts.order(:created_at).first
  end

  def membership_for(account)
    return nil if account.nil?

    memberships.find_by(account_id: account.id)
  end

  def member_of?(account)
    membership_for(account).present?
  end

  # Used by the Pundit policies. `admin` on the User record is the
  # instance-wide superuser flag from the starter template and is deliberately
  # NOT the same thing as being an admin of an account.
  def role_in(account)
    membership_for(account)&.role
  end
end
